FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["c:\\dev\\Beef\\Grill-Packages\\Serialize\\src\\Implementation\\IDeserializer.bf", "c:\\dev\\Beef\\Grill-Packages\\Toml\\src\\Internal\\Deserializer.bf", "src\\Program.bf", "c:\\dev\\Beef\\Grill-Packages\\Serialize\\src\\Attributes.bf", "Package.toml", "c:\\dev\\Beef\\Grill-Packages\\Toml\\BeefSpace.toml"]

[MainWindow]
X = 5
Y = 89
Width = 1094
Height = 943
ShowKind = "ShowNormal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 1918.0
RequestedHeight = 764.0
SizePriority = 1918.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 1656.04
RequestedHeight = 741.04
SizePriority = 741.04
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 215.0
RequestedHeight = 461.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.5
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1703.04
RequestedHeight = 459.0
SizePriority = 1703.04
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Attributes.bf"
TabWidth = 98.26923
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\dev\\Beef\\Grill-Packages\\Serialize\\src\\Attributes.bf"
CursorPos = 3864
VertPos = 2064.0
ProjectName = "Serialize"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "IDeserializer.bf"
TabWidth = 111.7308
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\dev\\Beef\\Grill-Packages\\Serialize\\src\\Implementation\\IDeserializer.bf"
CursorPos = 1213
ProjectName = "Serialize"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Deserializer.bf"
TabWidth = 108.8462
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\dev\\Beef\\Grill-Packages\\Toml\\src\\Internal\\Deserializer.bf"
CursorPos = 1780
VertPos = 816.0
ProjectName = "Toml"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 93.46154
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 2056
VertPos = 1200.0
ProjectName = "TestApp"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 227.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1918.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 84.61539
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 85.57693
TabIsPinned = false
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Diagnostics"
TabWidth = 114.4231
TabIsPinned = false
Type = "DiagnosticsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.11539
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 84.61539
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 191.0}, {Width = 191.0}, {Width = 191.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 75.96154
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 191.0}, {Width = 191.0}, {Width = 191.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1918.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 116.3462
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 95.19231
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 102.8846
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.6538
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 88.46154
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""
